//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public string id { get; set; }
        public Nullable<long> word_count { get; set; }
        public string pub_date { get; set; }
        public string headline { get; set; }
        public string thumbnail { get; set; }
        public string source { get; set; }
        public string lead_paragraph { get; set; }
        public string web_url { get; set; }
    }
}
